// let name = 'Mosh';
// console.log(name);

// // can not be reserved word
// // should be meaningful
// // can not start with a number 
// // can not contain a space or hyphen (-)

// let firstName = 'Mosh'; lastName = 'Iakobidze';




// let interestrate = 0.3;
// interestrate = 1;
// console.log(interestrate);

// // we can not reasign const if u need to reasing use let 




// let name = 'Mosh'; // stirng literal
// let age = 30; // Number literal
// let isApproved = true; // boolean literal
// let firstName = undefined; 
// let selectedColor = null;

// primitives are : stirng, number, boolean, undefined, null 
// references are : object array function 




// // languages static(statically-typed)  dynamic(dinamically-typed) Js 




// let person = {
//    name: 'Mosh',
//    age : 30,
// };

// person.name = "John";

// person['name'] = "Mary"; 

// console.log(person.name);


// let selectedColors = ['red', 'blue'];
// selectedColors[2] = 1;
// console.log(selectedColors.length);


// // functions 
// // pergorming a task 
// function greet (name,lastName) {
//     console.log("Hello" +' '+ name + " "+ lastName);
// }

// greet("John", 'Smith');


// calculating a value 
function square (number ) {
    return number * number ;
}

console.log(square(2));
