// var - declares a variable 
// let - declares a block variable 
//const - declares a block constant 
// if - marks a block of statements to be ececuted on a condination 
//switch - marks a block of statements to be executed in different classes
// for - Marks a block of statements to be executed in a loop
// funciton - declares a funcrtion 
// return - exits a function
// try - Implements erro handling to a bock of statement 